#!/usr/bin/env python3
"""AI-powered Q&A for pull requests using Anthropic's Claude API."""

import os
import sys
from pathlib import Path

import anthropic
from github import Auth, Github


def get_pr_diff() -> str:
    """Read the PR diff from file."""
    diff_file = Path("pr_diff.txt")
    if not diff_file.exists():
        print("Error: pr_diff.txt not found")
        sys.exit(1)
    return diff_file.read_text()


def extract_question(comment_body: str) -> str:
    """Extract the question from /ask_claude command."""
    if comment_body.startswith("/ask_claude "):
        return comment_body[12:].strip()
    return comment_body.strip()


def answer_question(
    question: str, diff: str, client: anthropic.Anthropic
) -> str:
    """Send the question and diff to Claude for answering."""
    system_prompt = (
        "You are a helpful assistant answering questions about code changes "
        "in a pull request. You have access to the PR diff.\n\n"
        "GUIDELINES:\n"
        "- Answer questions clearly and concisely\n"
        "- Reference specific files and line numbers when relevant\n"
        "- If the question cannot be answered from the diff, say so\n"
        "- Use markdown formatting for code snippets\n"
        "- Keep answers focused and helpful\n"
        "- If asked about potential issues, be honest but constructive"
    )

    user_prompt = (
        f"Here is the pull request diff:\n\n"
        f"```diff\n{diff}\n```\n\n"
        f"Question: {question}"
    )

    message = client.messages.create(
        model=os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-20250514"),
        max_tokens=2048,
        messages=[{"role": "user", "content": user_prompt}],
        system=system_prompt,
    )

    return message.content[0].text


def post_answer(answer: str, repo_name: str, pr_number: int) -> None:
    """Post the answer as a comment on the pull request."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Error: GITHUB_TOKEN not set")
        sys.exit(1)

    try:
        gh = Github(auth=Auth.Token(token))
        repo = gh.get_repo(repo_name)
        pr = repo.get_pull(pr_number)

        comment_body = (
            f"## :robot: AI Answer\n\n"
            f"{answer}\n\n"
            f"---\n"
            f"*This answer was generated by Claude AI based on the PR diff.*"
        )

        pr.create_issue_comment(comment_body)
        print(f"Posted answer to PR #{pr_number}")
    except Exception as e:
        print(f"Error posting answer to GitHub: {e}")
        sys.exit(1)


def main() -> None:
    """Main entry point for the AI Q&A."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY not set")
        sys.exit(1)

    repo_name = os.environ.get("REPO_NAME")
    pr_number_str = os.environ.get("PR_NUMBER")
    question_raw = os.environ.get("QUESTION", "")

    if not repo_name or not pr_number_str:
        print("Error: REPO_NAME and PR_NUMBER must be set")
        sys.exit(1)

    if not question_raw:
        print("Error: QUESTION not set")
        sys.exit(1)

    try:
        pr_number = int(pr_number_str)
    except ValueError:
        print(f"Error: PR_NUMBER '{pr_number_str}' is not a valid integer")
        sys.exit(1)

    question = extract_question(question_raw)

    if not question:
        print("Error: No question provided after /ask_claude")
        sys.exit(1)

    print(f"Answering question for {repo_name}#{pr_number}")
    print(f"Question: {question}")

    diff = get_pr_diff()
    if not diff.strip():
        print("No changes detected in the pull request")
        return

    # Truncate very large diffs
    max_diff_chars = 100000
    if len(diff) > max_diff_chars:
        diff = diff[:max_diff_chars] + "\n\n... (diff truncated)"
        print(f"Diff truncated to {max_diff_chars} characters")

    client = anthropic.Anthropic(api_key=api_key)

    print("Getting answer from Claude...")
    answer = answer_question(question, diff, client)

    print("Posting answer...")
    post_answer(answer, repo_name, pr_number)

    print("Done!")


if __name__ == "__main__":
    main()
