#!/usr/bin/env python3
"""AI-powered code review using Anthropic's Claude API."""

import os
import sys
from pathlib import Path

import anthropic
from github import Github


def get_pr_diff() -> str:
    """Read the PR diff from file."""
    diff_file = Path("pr_diff.txt")
    if not diff_file.exists():
        print("Error: pr_diff.txt not found")
        sys.exit(1)
    return diff_file.read_text()


def analyze_code_with_claude(diff: str, client: anthropic.Anthropic) -> str:
    """Send the diff to Claude for analysis."""
    system_prompt = """You are an expert code reviewer. Analyze the provided git diff and provide a constructive code review.

Focus on:
1. **Bugs and Issues**: Identify potential bugs, logic errors, or edge cases that aren't handled
2. **Security**: Flag any security vulnerabilities or concerns
3. **Performance**: Note any performance issues or inefficiencies
4. **Best Practices**: Suggest improvements for code quality, readability, and maintainability
5. **Testing**: Comment on test coverage if tests are included in the diff

Guidelines:
- Be constructive and helpful, not harsh
- Prioritize important issues over style nitpicks
- If the code looks good, say so briefly
- Format your response in clear markdown
- Keep the review concise but thorough
- Reference specific line numbers or code snippets when discussing issues"""

    user_prompt = f"""Please review the following pull request diff and provide feedback:

```diff
{diff}
```

Provide a structured code review with sections for any issues found. If the changes look good, provide a brief positive summary."""

    message = client.messages.create(
        model="claude-sonnet-4-5-20250514",
        max_tokens=4096,
        messages=[{"role": "user", "content": user_prompt}],
        system=system_prompt,
    )

    return message.content[0].text


def post_review_comment(review: str, repo_name: str, pr_number: int) -> None:
    """Post the review as a comment on the pull request."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("Error: GITHUB_TOKEN not set")
        sys.exit(1)

    gh = Github(token)
    repo = gh.get_repo(repo_name)
    pr = repo.get_pull(pr_number)

    comment_body = f"""## 🤖 AI Code Review

{review}

---
*This review was generated by Claude AI. Please use your judgment when considering these suggestions.*"""

    pr.create_issue_comment(comment_body)
    print(f"Successfully posted review comment to PR #{pr_number}")


def main() -> None:
    """Main entry point for the AI code review."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("Error: ANTHROPIC_API_KEY not set")
        sys.exit(1)

    repo_name = os.environ.get("REPO_NAME")
    pr_number_str = os.environ.get("PR_NUMBER")

    if not repo_name or not pr_number_str:
        print("Error: REPO_NAME and PR_NUMBER must be set")
        sys.exit(1)

    pr_number = int(pr_number_str)

    print(f"Starting AI code review for {repo_name}#{pr_number}")

    diff = get_pr_diff()
    if not diff.strip():
        print("No changes detected in the pull request")
        return

    # Truncate very large diffs to avoid token limits
    max_diff_chars = 100000
    if len(diff) > max_diff_chars:
        diff = diff[:max_diff_chars] + "\n\n... (diff truncated due to size)"
        print(f"Diff truncated to {max_diff_chars} characters")

    client = anthropic.Anthropic(api_key=api_key)

    print("Analyzing code with Claude...")
    review = analyze_code_with_claude(diff, client)

    print("Posting review comment...")
    post_review_comment(review, repo_name, pr_number)

    print("AI code review completed successfully!")


if __name__ == "__main__":
    main()
