repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=80"]
        exclude: ^src/sabr/_anarci/

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=80"]
        exclude: ^src/sabr/_anarci/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^src/sabr/_anarci/
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
        args:
          - "--max-line-length=80"
          - "--extend-ignore=E203,W503"

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        exclude: ^src/sabr/_anarci/
        args:
          - "--disable=all"
          - "--enable=C0415"
          - "--score=n"
        name: pylint (no lazy imports)
