version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install .[docs]
    - pdoc sabr --docformat google -o $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
