version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install .
    - pip install pdoc
    # Copy README into package directory so it's always found regardless of install location
    - cp README.md src/sabr/README.md
    - JAX_PLATFORMS=cpu pdoc ./src/sabr --docformat google -o $READTHEDOCS_OUTPUT/html
