version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    # Install dependencies (but we'll run pdoc on source dir to keep README.md accessible)
    - pip install .
    - pip install pdoc
    # Use source path so __file__ resolves to src/sabr and README.md can be found
    - JAX_PLATFORMS=cpu pdoc ./src/sabr --docformat google -o $READTHEDOCS_OUTPUT/html
