[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sabr"
version = "0.1.0"
description = "Structure-based Antibody Renumbering"
readme = "README.md"
requires-python = ">=3.9"

authors = [
  { name = "Diego del Alamo" }
]

# SoftAlign is vendored as a submodule, so no external dependency
dependencies = []

[project.urls]
Homepage = "https://github.com/delalamo/SAbR"

[tool.setuptools.packages.find]
where = ["src", "external/SoftAlign"]
include = ["sabr*", "softalign*"]
exclude = ["external/SoftAlign/models*"]

[tool.setuptools]
include-package-data = true
