[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sabr-kit"
version = "0.1.2"
description = "Structure-based Antibody Renumbering"
readme = "README.md"
requires-python = ">=3.9"

authors = [
  { name = "Diego del Alamo" }
]

dynamic = ["dependencies"]

[project.optional-dependencies]
test = ["pytest>=8.0", "pytest-cov>=5.0", "numpy>=1.24"]

[project.scripts]
sabr = "sabr.cli:main"

[project.urls]
Homepage = "https://github.com/delalamo/SAbR"

[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80

[tool.flake8]
max-line-length = 80
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.setuptools]
packages = ["sabr", "softalign", "ANARCI"]
include-package-data = true

[tool.setuptools.package-dir]
sabr = "src/sabr"
softalign = "external/SoftAlign/softalign"
ANARCI = "external/ANARCI/src/ANARCI"

[tool.setuptools.package-data]
sabr = ["assets/embeddings.npz"]
softalign = ["models/*"]

[tool.setuptools.dynamic]
dependencies = {file = ["external/SoftAlign/requirements.txt"]}
