[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sabr"
version = "0.1.1.dev2"  # bump for TestPyPI re-upload
description = "Structure-based Antibody Renumbering"
readme = "README.md"
requires-python = ">=3.9"

authors = [
  { name = "Diego del Alamo" }
]

dependencies = []

[project.urls]
Homepage = "https://github.com/delalamo/SAbR"

[tool.setuptools]
packages = ["sabr", "softalign"]
include-package-data = true

[tool.setuptools.package-dir]
sabr = "src/sabr"
softalign = "external/SoftAlign/softalign"
