name: "Checkout and Setup Python"
description: "Checkout repository and set up Python with optional submodules"

inputs:
  python-version:
    description: "Python version to set up"
    required: false
    default: "3.11"
  submodules:
    description: "Whether to checkout submodules"
    required: false
    default: "false"
  fetch-depth:
    description: "Number of commits to fetch (0 for all history)"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
