name: "Prepare Build Environment"
description: "Upgrade pip and install build tools"

inputs:
  extra-packages:
    description: "Additional packages to install (space-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Upgrade pip and install build tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install build twine ${{ inputs.extra-packages }}
