name: Build and Publish Docker Image

on:
  push:
    branches:
      - "**" # Trigger on all branches while testing

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed to push to GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # equivalent to --recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch  # adds branch-specific tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Test installation inside container
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest bash -c "
            git clone --recursive https://github.com/delalamo/SAbR.git &&
            cd SAbR &&
            pip install -e . &&
            python -c 'import ANARCI, softalign, sabr; print(\"Success!\")'
          "
